In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../datasets/cardio_train.csv", sep=";")

In [3]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [5]:
print("Shape :", df.shape)
print("\nColumns :",df.columns)
print("\nNull values: ",df.isnull().sum())
print("\nTotal duplicate: ", df.duplicated().sum())

Shape : (70000, 13)

Columns : Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='str')

Null values:  id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

Total duplicate:  0

In [6]:
#target
df["cardio"].value_counts()

cardio
0    35021
1    34979
Name: count, dtype: int64

In [7]:
#statistics 
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
#Check unique values
for col in df.columns:
    print("\n---", col , "---")
    print(df[col].unique()[:20])

--- id ---
[ 0  1  2  3  4  8  9 12 13 14 15 16 18 21 23 24 25 27 28 29]

--- age ---
[18393 20228 18857 17623 17474 21914 22113 22584 17668 19834 22530 18815
 14791 19809 14532 16782 21296 16747 17482 21755]

--- gender ---
[2 1]

--- height ---
[168 156 165 169 151 157 178 158 164 173 181 172 170 154 162 163 153 159
 166 155]

--- weight ---
[ 62.  85.  64.  82.  56.  67.  93.  95.  71.  68.  80.  60.  78. 112.
  75.  52.  83.  69.  90.  45.]

--- ap_hi ---
[110 140 130 150 100 120 145 170 135 125  90 180 160 133 190  80 122 169
 126 158]

--- ap_lo ---
[  80   90   70  100   60   85   89  110   65   63   79 1100 1000  800
  120   50   30  109   84 1033]

--- cholesterol ---
[1 3 2]

--- gluc ---
[1 2 3]

--- smoke ---
[0 1]

--- alco ---
[0 1]

--- active ---
[1 0]

--- cardio ---
[0 1]

In [9]:
print("Invalid ap_hi:", ((df["ap_hi"] < 70) | (df["ap_hi"] > 250)).sum())
print("Invalid ap_lo:", ((df["ap_lo"] < 40) | (df["ap_lo"] > 150)).sum())
print("\n\n")
print(df.loc[
    (df["ap_hi"] < 70) | (df["ap_hi"] > 250),
    ["age", "height", "weight", "ap_hi", "ap_lo", "cardio"]
])

Invalid ap_hi: 229
Invalid ap_lo: 1034



         age  height  weight  ap_hi  ap_lo  cardio
567    21281     168    78.0     14     90       1
927    21867     175    70.0     14     90       1
979    18225     172    65.0     11     80       0
1600   19201     165    66.0     12     80       0
1627   22591     165    71.0     14     80       1
...      ...     ...     ...    ...    ...     ...
68742  18755     158    74.0     14     90       1
68998  19107     154    77.0     14     90       0
69137  15442     176    65.0     12     80       0
69370  14696     170    74.0   2000    100       1
69549  21243     155    69.0     13     90       1

[229 rows x 6 columns]

In [10]:
print(df.loc[
    (df["ap_lo"] < 40) | (df["ap_lo"] > 150),
    ["age", "height", "weight", "ap_hi", "ap_lo", "cardio"]
])

         age  height  weight  ap_hi  ap_lo  cardio
228    17489     183    98.0    160   1100       1
241    21932     157    60.0    160   1000       1
260    18217     150    83.0    140    800       1
329    23407     176    63.0    160   1000       1
345    18704     154    81.0    140   1000       1
...      ...     ...     ...    ...    ...     ...
69771  23330     167    81.0    160   1000       1
69872  21808     152    56.0    160   1000       1
69878  21239     168    95.0    160   1000       1
69885  22417     166    78.0    170   1000       0
69967  21416     168    63.0    140   1000       1

[1034 rows x 6 columns]

In [11]:
print("Invalid height:", ((df["height"] < 120) | (df["height"] > 220)).sum())
print("Invalid weight:", ((df["weight"] < 30) | (df["weight"] > 200)).sum())
print("\n\n")
print(df.loc[
    (df["height"] < 120) | (df["height"] > 220),
    ["age", "height", "weight", "ap_hi", "ap_lo", "cardio"]
])

Invalid height: 53
Invalid weight: 7



         age  height  weight  ap_hi  ap_lo  cardio
224    21800      76    55.0    120     80       0
3420   14516     100    70.0    100     70       0
6486   21220     250    86.0    140    100       1
7116   20579     117    78.0    150     90       1
7598   14661      70    72.0    120      8       0
8171   17646      97   170.0    160    100       1
8677   19698     119    89.0    160     90       1
11230  18307     110    90.0    120     80       0
12770  19594      75   168.0    120     80       1
13265  22456      71    68.0    120     80       0
14323  22005      67    57.0    120     90       1
15167  15812      70    68.0    120     80       0
16699  19680      74    98.0    140     90       1
17074  21259     100    86.0    110     70       1
17277  17530      98    45.0     12     80       0
20028  19777     112   167.0    180    120       0
22542  14538      68    65.0    100     60       0
22723  23386      55    81.0    130     90       1
23913  19074      81   156.0    140     90       0
27384  15292      80   178.0    140     90       1
27603  20978      64    61.0    130     70       0
28737  19747      91    55.0    140     90       1
28897  18961     110   105.0    140     90       1
29157  19088      60    69.0    110     70       0
29735  17453     109    64.0    140     80       1
32098  15374      72    74.0    150     90       1
33607  19709      65    72.0    130     80       0
34364  21888     110    70.0    110     70       1
37388  22051     105    72.0    120     70       0
39543  14606     108    70.0    140     90       1
41807  23319     109    68.0    120     80       1
44490  19120      65    60.0    120     80       0
45091  18130     110    70.0    110     70       0
45358  19834     104   159.0    200    100       1
46043  18739     111    69.0    130     90       1
46319  21006      68    71.0    120     80       0
47352  23297      75    75.0    120     80       0
50136  23422     113    73.0    120     80       0
50789  14499      67    60.0    110     80       0
51459  15432      70    69.0    120     80       0
53344  20541      67    80.0    120     80       1
56022  21171      96    59.0     90     60       1
58868  14680     100    60.0    100     60       0
59625  17643     104   165.0    120     80       0
59738  16970     110    68.0    110     70       0
59960  21227     117    70.0    110     60       1
60691  17377     110    70.0    110     70       1
64115  18426      59    57.6    125     67       0
64454  21348      66    63.0     12     80       1
64787  23476     105    80.0    130     90       1
65302  18467      99    60.0     90     60       0
66479  16928     110    90.0    110     90       0
66643  18830      57    61.0    130     90       1

In [12]:
print(df.loc[
    (df["weight"] < 30) | (df["weight"] > 200),
    ["age", "height", "weight", "ap_hi", "ap_lo", "cardio"]
])

         age  height  weight  ap_hi  ap_lo  cardio
26806  23284     157    23.0    110     80       0
29488  20408     177    22.0    120     80       0
33817  21582     178    11.0    130     90       1
34276  14664     128    28.0    120     80       0
57858  18804     165    10.0    180   1100       1
60188  21855     162    21.0    120     80       1
60699  18875     171    29.0    110     70       1

In [13]:
invalid_mask = (
    (df["ap_hi"] < 70) | (df["ap_hi"] > 250) |
    (df["ap_lo"] < 40) | (df["ap_lo"] > 150) |
    (df["height"] < 120) | (df["height"] > 220) |
    (df["weight"] < 30) | (df["weight"] > 200)
)

print("Total invalid rows:", invalid_mask.sum())

Total invalid rows: 1302

In [14]:
print("Original rows:", len(df))
print("Invalid rows:", invalid_mask.sum())
print("Rows after cleaning:", len(df) - invalid_mask.sum())
print("Percentage retained:", (1 - invalid_mask.mean()) * 100)

Original rows: 70000
Invalid rows: 1302
Rows after cleaning: 68698
Percentage retained: 98.14

In [15]:
df_clean = df[~invalid_mask].copy()

print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

print("Invalid ap_hi:", ((df_clean["ap_hi"] < 70) | (df_clean["ap_hi"] > 250)).sum())
print("Invalid ap_lo:", ((df_clean["ap_lo"] < 40) | (df_clean["ap_lo"] > 150)).sum())
print("Invalid height:", ((df_clean["height"] < 120) | (df_clean["height"] > 220)).sum())
print("Invalid weight:", ((df_clean["weight"] < 30) | (df_clean["weight"] > 200)).sum())

Original shape: (70000, 13)
Cleaned shape: (68698, 13)
Invalid ap_hi: 0
Invalid ap_lo: 0
Invalid height: 0
Invalid weight: 0